plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
}
apply plugin: 'io.spring.dependency-management'

group = 'org.challenge'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:2.0.1"
    }
}

dependencies {
    implementation('org.springframework.boot:spring-boot-starter')
    implementation('org.springframework.ai:spring-ai-starter-model-openai')
    implementation('org.springframework.boot:spring-boot-starter-webmvc')
    implementation('org.springframework.boot:spring-boot-starter-data-jpa')
    implementation('org.springframework.boot:spring-boot-starter-validation')
    implementation('org.springframework.boot:spring-boot-h2console')

    runtimeOnly('com.h2database:h2')

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation('org.springframework.boot:spring-boot-starter-test')
    testImplementation('org.springframework.boot:spring-boot-webmvc-test')
    testImplementation('org.junit.jupiter:junit-jupiter')
    testImplementation('com.tngtech.archunit:archunit-junit5:1.5.0')
    testImplementation('jakarta.persistence:jakarta.persistence-api:3.2.0')
    testImplementation('com.github.javaparser:javaparser-core:3.27.0')
    testImplementation('com.squareup.okhttp3:mockwebserver:4.12.0')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}
